# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

        
      # run tests!
      - run:
          name: run tests
          command: |
	    pip3 install numpy --user
            cd python
            cd test
            ./run_tests

      - store_artifacts:
          path: test-reports
          destination: test-reports
          